config:
  maintainer: John Doe
  app:
    name: Laravel Filament App
    description: My App
  registry:
    url: ghcr.io
    username: jawaracloud
    image: laravel-filament
  sonarqube:
    project_key: jenkins-laravel
