config:
  maintainer: Tra
  app:
    name: Laravel Filament App
    description: My App
    domain: http://localhost
  registry:
    url: ghcr.io
    username: jawaracloud
    image: laravel-filament
  sonarqube:
    project_key: jenkins-laravel
